const tl = gsap.timeline({ defaults: { ease: 'power4' } })
const tl2 = gsap.timeline({ defaults: { duration: 1.5, delay: 1 } })
AOS.init()
tl.to('.navbar', { opacity: 0, duration: 0 })
tl.to('.intro', { y: '-100%', duration: 1.2, delay: 3.7 })
tl.to('.navbar', { opacity: 1, duration: 1 })
tl.from('.hero-text', { y: '100%', opacity: 0, duration: 1 })
tl.from('.hero-img', { y: '100%', opacity: 0, duration: 1 })
tl2.to('.hero-img img', { y: 15, repeat: -1, yoyo: true, duration: 2 })